#spring.application.name=spring

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umc_study
    username: root
    password: ""
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

springdoc:
    swagger-ui:
      # 각 API의 그룹 표시 순서
      # path, query, body, response 순으로 출력
      groups-order : DESC

      # 태그 정렬 순서
      # 알파벳 순 정렬
      tags-sorter: alpha

      # 컨트롤러 정렬 순서
      # method는 delete - get - patch - post - put 순으로 정렬
      operations-sorter: method

      # swagger-ui default url인 petstore html의 비활성화 설정
      disable-swagger-default-url: true

      # swagger-ui에서 try 했을 때 request duration을 알려주는 설정
      display-request-duration: true

      # 모델 확장 깊이를 2단계로 설정
      default-models-expand-depth: 2

      # 개별 API 호출의 모델 확장 깊이를 2단계로 설정
      default-model-expand-depth: 2
    api-docs :
      # OpenAPI 명세서의 경로를 /api/docs로 설정
      # 기본값 : /v3/api-docs
      path:  /api-docs

    # Spring Actuator의 엔드포인트를 Swagger에 표시
    show-actuator: true

    # API에서 사용할 기본 미디어 유형을 application/json으로 설정
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

    # Swagger UI에서 출력 포맷을 pretty-print 방식으로 설정
    writer-with-default-pretty-printer: true

    # Swagger API에서 Spring의 ModelAndView 객체를 허용
    model-and-view-allowed: true

    # Swagger 문서에 포함할 경로 패턴을 지정
    paths-to-match: /**